# Sass Linter Options
# File Options
files:
  include:
    - 'components/**/*.s+(a|c)ss'
    - 'constants/sass/*.s+(a|c)ss'
    - 'constants/sass/**/*.s+(a|c)ss'
  ignore:
    - 'node_modules'

# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  class-name-format: 0
  nesting-depth: 0
  no-duplicate-properties: 0
  leading-zero: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq

  no-warn: 1
  no-debug: 1
  no-ids: 2
  no-important: 1
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order: 2
  force-pseudo-nesting: 2
  force-element-nesting: 2