version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-2-{{ checksum "yarn.lock" }}

      - run:
          name: Install Node dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
            yarn install

      - save_cache:
          key: dependency-cache-2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      - run:
          name: Linting Build
          command: yarn lint

      - run:
          name: Running Tests
          command: yarn test

      - run:
          name: Running Integration Tests
          command: yarn test:integration

      - run:
          name: Build package
          command: yarn build

      - store_artifacts:
          name: Saving visual regression snapshots
          path: ~/integration/__image_snapshots__

      - run:
          name: Configure Git
          command: |
            git config user.email "engineering@unitedincome.com"
            git config user.name "United Income Engineering"

      - deploy:
          name: Publish to NPM
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm version patch -m "Bumping up version to %s [skip ci]"
              npm publish
              git push --set-upstream origin $CIRCLE_BRANCH
            fi

