version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v2-{{ checksum "yarn.lock" }}

      - run:
          name: Install Node dependencies
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
            yarn install

      - save_cache:
          key: dependency-cache-v2-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      - run:
          name: Linting Build
          command: yarn lint

      - run:
          name: Run unit tests
          command: |
            mkdir -p ./reports/tape
            yarn testCI

      - run:
          name: Verifying build
          command: yarn build --mode=production

      - run:
          name: Push coverage report to CodeCov
          command: |
            echo $CODECOV_TOKEN
            bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN} -f coverage/lcov.info -F unit

      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
          destination: tests/

      # Persist everything for StoryBook
      - persist_to_workspace:
          root: .
          paths:
            - .

  smoke_test:
    docker:
      - image: circleci/node:10.16
    resource_class: small
    environment:
      NODE_ENV: production
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run IE11 Smoke Test
          command: |
            if [ "${CIRCLE_BRANCH}" != "develop" ]; then
              yarn browserstack
            fi

  publish_package:
    docker:
      - image: circleci/node:10.16
    resource_class: small
    environment:
      NODE_ENV: production
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Configure Git
          command: |
            # Add the GitHub public key so pushing doesn't ask for verification.
            # Typically, this is setup by the 'checkout' step, but we don't use that here;
            # we take an artifact from the workspace instead of re-building a snapshot from source.
            # If builds stop running to completion at some point, it may be because
            # the GitHub public key changed and needs updated here.
            mkdir -p ~/.ssh
            echo "github.com ssh-rsa ${GITHUB_PUBLIC_KEY}" \>> ~/.ssh/known_hosts
            (umask 077; touch ~/.ssh/id_rsa)
            chmod 0600 ~/.ssh/id_rsa
            (cat \<<EOF > ~/.ssh/id_rsa
            $CHECKOUT_KEY
            EOF
            )

            # Use git+ssh instead of https
            git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
            git config --global gc.auto 0 || true
            git config user.email "engineering@unitedincome.com"
            git config user.name "United Income Engineering"

      - deploy:
          name: Publish to NPM
          command: |
            rm -rf dist/**/*.spec.d.ts dist/**/*.story.d.ts dist/nightwatch dist/utils-for-tests
            npm version patch -m "Bump version to %s [skip ci]"
            npm publish
            git push --set-upstream origin $CIRCLE_BRANCH --tags

workflows:
  version: 2.1 # Required due to some issue with Percy builds
  components:
    jobs:
      - build:
          context: Development
          filters:
            branches:
              ignore:
                - gh-pages
      - smoke_test:
          context: Development
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - publish_package:
          context: Development
          requires:
            - build
          filters:
            branches:
              only:
                - master
