name: deployment-prod
on:
  push:
    branches:
      - master
jobs:
  publish_storybook:
    runs-on: ubuntu-latest
    # Prevents automatic version bumps from triggering the deployment job twice.
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false 

      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install
        run: yarn install

      - name: Install InVision .dsmrc
        run: |
          echo '{
            "authToken": "${{ secrets.DSM_AUTH_TOKEN }}",
            "dsmHost": "${{ secrets.DSM_HOST }}",
            "organization": "${{ secrets.DSM_ORG }}",
            "outputDir": ".dsm",
            "storyPath": "components/**/**/*.story.jsx"
          }' > '.dsmrc'

      - name: Publish InVision DSM
        run: yarn dsm-storybook:publish

      - name: Cleanup InVision Temp Files
        run: rm -rf .dsmrc && rm -rf .dsm

      - name: Build
        run: yarn build

      - name: Run Percy Tests
        uses: percy/storybook-action@v0.1.1
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Build Storybook
        run: yarn buildStorybook

      - name: Deploy to GitHub Pages
        # Docs: https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: '.build'
          CLEAN: true
          CLEAN_EXCLUDE: '["develop"]'
          COMMIT_MESSAGE: '[skip ci]' 
